networks:
  mes-network:
    driver: bridge

services:
  api:
    image: '${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}'
    command: ["node", "dist/main"]
    env_file:
      - .env
    # Backend port NOT exposed externally - only accessible internally via Docker network
    networks:
      - mes-network
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      # NOTE: Changed to 4001 to match your Dockerfile expose port. 
      # If your app actually runs on 4000, change this back to 4000.
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    networks:
      - mes-network
    # Removed the environment block! The env_file will inject the secrets automatically.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    networks:
      - mes-network
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    healthcheck:
      # Updated to include the password so the ping is authorized
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
