networks:
  mes-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:

services:
  api:
    image: '${CI_REGISTRY_IMAGE:-mes-backend}:${CI_COMMIT_SHA:-latest}'
    command: ["node", "dist/main"]
    networks:
      - mes-network
    # THIS LOADS YOUR ENTIRE .ENV FILE AT ONCE!
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    networks:
      - mes-network
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Hardcoded to match your .env to guarantee healthcheck passes
      test: ['CMD-SHELL', 'pg_isready -U admin -d dannie_mes']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - mes-network
    env_file:
      - .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
